name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    environment: ttt-env
    steps:
      - run: pwd
      - run: ls
      - uses: actions/checkout@v3
      - run: pwd
      - run: ls
      - run: touch ttt
      - run: echo ${{secrets.PPZ_NAME}} > ./ttt
      - run: mv ./ttt ./ttt.haha
      - run: echo notkey >> ./ttt.haha
      - run: cat ./ttt.haha
